#外部引入包
yarn add --dev es6-shim
yarn add --dev lodash
yarn add --dev jquery@1.11.3
yarn add --dev jquery-ui@1.12.1
yarn add --dev moment 
yarn add --dev antd
yarn add --dev prop-types
yarn add --dev react 
yarn add --dev react-dom 
yarn add --dev react-router-dom
yarn add --dev intl
yarn add --dev react-intl
yarn add --dev mobx@4.3.1
yarn add --dev mobx-react
#类型声明文件
yarn add --dev @types/intl
yarn add --dev @types/react-intl
yarn add --dev @types/lodash
yarn add --dev @types/jquery
yarn add --dev @types/react
yarn add --dev @types/react-dom
yarn add --dev @types/react-router-dom
#打包常用包
yarn add --dev cross-env
yarn add --dev webpack 
yarn add --dev webpack-cli 
yarn add --dev webpack-dev-server
yarn add --dev style-loader 
yarn add --dev css-loader
yarn add --dev less@2.7.3
yarn add --dev less-loader
yarn add --dev url-loader
yarn add --dev typescript 
yarn add --dev awesome-typescript-loader 
yarn add --dev source-map-loader
yarn add --dev tslint
yarn add --dev tslint-react
#webpack常用插件
yarn add --dev extract-text-webpack-plugin
yarn add --dev friendly-errors-webpack-plugin
yarn add --dev open-browser-webpack-plugin
yarn add --dev copy-webpack-plugin
yarn add --dev html-webpack-plugin
#yarn add --dev uglifyjs-webpack-plugin
#yarn add --dev clean-webpack-plugin
#yarn add --dev webpack-common-shake
#yarn add --dev duplicate-package-checker-webpack-plugin
#yarn add --dev optimize-css-assets-webpack-plugin
#yarn add --dev webpack-parallel-uglify-plugin
#yarn add --dev lodash-webpack-plugin
#yarn add --dev stylelint-webpack-plugin
